
/* DO NOT EDIT! This is an autogenerated file. See scripts/buildcommands.py. */

#include "../../include/board/irq.h"
#include "../../include/generic/pgm.h"
#include "../../include/printer/command.h"
#include "../../include/printer/compiler.h"
#include "../../include/hal_call/initial_pins.h"
#include "../../include/bus/share_space.h"
#include "../../include/bus/msgboxx.h"
void
ctr_run_initfuncs(void)
{
#if MSGBOX_EN
    msgboxx_init();
#endif
    share_space_clear();
    share_space_init();
    extern void alloc_init(void);
    alloc_init();
    extern void initial_pins_setup(void);
    initial_pins_setup();
    extern void watchdog_init(void);
    watchdog_init();
    extern void timer_init(void);
    timer_init();
    // extern void usb_init(void);
    // usb_init();
    extern void chipid_init(void);
    chipid_init();

    

}

void
ctr_run_shutdownfuncs(void)
{
    extern void sendf_shutdown(void);
    sendf_shutdown();
    extern void move_reset(void);
    move_reset();
    extern void digital_out_shutdown(void);
    digital_out_shutdown();
    extern void stepper_shutdown(void);
    stepper_shutdown();
    extern void trsync_shutdown(void);
    trsync_shutdown();
    extern void analog_in_shutdown(void);
    analog_in_shutdown();
    extern void spidev_shutdown(void);
    spidev_shutdown();
    extern void st7920_shutdown(void);
    st7920_shutdown();
    extern void hd44780_shutdown(void);
    hd44780_shutdown();
    extern void tmcuart_shutdown(void);
    tmcuart_shutdown();
    extern void clear_active_irq(void);
    clear_active_irq();
    extern void timer_reset(void);
    timer_reset();
    // extern void usb_shutdown(void);
    // usb_shutdown();
}

void
ctr_run_taskfuncs(void)
{
    irq_poll();
    extern void trsync_task(void);
    trsync_task();
    // irq_poll();
    irq_poll();
    extern void analog_in_task(void);
    analog_in_task();
    irq_poll();
    // extern void thermocouple_task(void);
    // thermocouple_task();
    // irq_poll();
    extern void adxl345_task(void);
    adxl345_task();
    irq_poll();
    extern void buttons_task(void);
    buttons_task();
    irq_poll();
    extern void tmcuart_task(void);
    tmcuart_task();
    irq_poll();
    extern void counter_task(void);
    counter_task();
    irq_poll();
    extern void watchdog_reset(void);
    watchdog_reset();
    irq_poll();
    extern void timer_task(void);
    timer_task();
    irq_poll();
    extern void usb_ep0_task(void);
    usb_ep0_task();
    irq_poll();
    extern void usb_bulk_out_task(void);
    usb_bulk_out_task();
    irq_poll();
    extern void usb_bulk_in_task(void);
    usb_bulk_in_task();
    irq_poll();
}

uint8_t __always_inline
ctr_lookup_static_string(const char *str)    //-CMD-G-G-2022-07-21---
{
    if (__builtin_strcmp(str, "Shutdown cleared when not shutdown") == 0)
        return 2;
    if (__builtin_strcmp(str, "Timer too close") == 0) //-MOVE-G-G-2022-07-21--
        return 3;
    if (__builtin_strcmp(str, "sentinel timer called") == 0)
        return 4;
    if (__builtin_strcmp(str, "Invalid command") == 0)
        return 5;
    if (__builtin_strcmp(str, "Message encode error") == 0)
        return 6;
    if (__builtin_strcmp(str, "Command parser error") == 0)
        return 7;
    if (__builtin_strcmp(str, "Command request") == 0)
        return 8;
    if (__builtin_strcmp(str, "config_reset only available when shutdown") == 0)
        return 9;
    if (__builtin_strcmp(str, "oids already allocated") == 0)
        return 10;
    if (__builtin_strcmp(str, "Can't assign oid") == 0)
        return 11;
    if (__builtin_strcmp(str, "Invalid oid type") == 0)
        return 12;
    if (__builtin_strcmp(str, "Already finalized") == 0)
        return 13;
    if (__builtin_strcmp(str, "Invalid move request size") == 0)
        return 14;
    if (__builtin_strcmp(str, "Move queue overflow") == 0)
        return 15;
    if (__builtin_strcmp(str, "alloc_chunks failed") == 0)
        return 16;
    if (__builtin_strcmp(str, "alloc_chunk failed") == 0)
        return 17;
    if (__builtin_strcmp(str, "update_digital_out not valid with active queue") == 0)
        return 18;
    if (__builtin_strcmp(str, "Scheduled digital out event will exceed max_duration") == 0)
        return 19;
    if (__builtin_strcmp(str, "Can not set soft pwm cycle ticks while updates pending") == 0)
        return 20;
    if (__builtin_strcmp(str, "Missed scheduling of next digital out event") == 0)
        return 21;
    if (__builtin_strcmp(str, "Can't reset time when stepper active") == 0)
        return 22;
    if (__builtin_strcmp(str, "Invalid count parameter") == 0)
        return 23;
    if (__builtin_strcmp(str, "Stepper too far in past") == 0)
        return 24;
    if (__builtin_strcmp(str, "Can't add signal that is already active") == 0)
        return 25;
    if (__builtin_strcmp(str, "ADC out of range") == 0)
        return 26;
    if (__builtin_strcmp(str, "Invalid spi config") == 0)
        return 27;
    if (__builtin_strcmp(str, "Thermocouple reader fault") == 0)
        return 28;
    if (__builtin_strcmp(str, "Thermocouple ADC out of range") == 0)
        return 29;
    if (__builtin_strcmp(str, "Invalid thermocouple chip type") == 0)
        return 30;
    if (__builtin_strcmp(str, "i2c_modify_bits: Odd number of bits!") == 0)
        return 31;
    if (__builtin_strcmp(str, "Invalid buttons retransmit count") == 0)
        return 32;
    if (__builtin_strcmp(str, "Set button past maximum button count") == 0)
        return 33;
    if (__builtin_strcmp(str, "Max of 8 buttons") == 0)
        return 34;
    if (__builtin_strcmp(str, "tmcuart data too large") == 0)
        return 35;
    if (__builtin_strcmp(str, "Invalid neopixel update command") == 0)
        return 36;
    if (__builtin_strcmp(str, "Invalid neopixel data_size") == 0)
        return 37;
    if (__builtin_strcmp(str, "Not a valid input pin") == 0)
        return 38;
    if (__builtin_strcmp(str, "Not an output pin") == 0)
        return 39;
    if (__builtin_strcmp(str, "Rescheduled timer in the past") == 0)    //-CMD-G-G-2022-07-21--
        return 40;
    if (__builtin_strcmp(str, "Not a valid ADC pin") == 0)
        return 41;
    if (__builtin_strcmp(str, "Failed to send i2c addr") == 0)
        return 42;
    if (__builtin_strcmp(str, "i2c timeout") == 0)
        return 43;
    if (__builtin_strcmp(str, "Unsupported i2c bus") == 0)
        return 44;
    if (__builtin_strcmp(str, "Invalid spi bus") == 0)
        return 45;
    return 0xff;
}

const struct initial_pin_s initial_pins[] PROGMEM = {
};
const int initial_pins_size PROGMEM = ARRAY_SIZE(initial_pins);

// extern void DefaultHandler(void);
// extern uint32_t _stack_end;
// extern void ResetHandler(void);
extern void OTG_FS_IRQHandler(void);
// extern void SysTick_Handler(void);

// const void *VectorTable[] __visible __section(".vector_table") = {
//     &_stack_end,
//     ResetHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     SysTick_Handler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     DefaultHandler,
//     OTG_FS_IRQHandler,
// };

static const uint8_t command_parameters0[] PROGMEM = {
    PT_uint16 };
static const uint8_t command_parameters1[] PROGMEM = {
    PT_uint32, PT_uint16 };
static const uint8_t command_parameters2[] PROGMEM = {
    PT_uint32, PT_progmem_buffer };
static const uint8_t command_parameters3[] PROGMEM = {
    PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters4[] PROGMEM = {
    PT_uint32, PT_uint32 };
static const uint8_t command_parameters5[] PROGMEM = {
    PT_uint32 };
static const uint8_t command_parameters6[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16, PT_byte };
static const uint8_t command_parameters7[] PROGMEM = {
    PT_buffer };
static const uint8_t command_parameters8[] PROGMEM = {
    PT_byte, PT_int32 };
static const uint8_t command_parameters9[] PROGMEM = {
    PT_byte, PT_byte, PT_uint32, PT_byte };
static const uint8_t command_parameters10[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters11[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16 };
static const uint8_t command_parameters12[] PROGMEM = {
    PT_byte, PT_buffer };
static const uint8_t command_parameters13[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte };
static const uint8_t command_parameters14[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint16, PT_uint16 };
static const uint8_t command_parameters15[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32 };
static const uint8_t command_parameters16[] PROGMEM = {
    PT_byte, PT_uint16, PT_buffer };
static const uint8_t command_parameters17[] PROGMEM = {
    PT_byte, PT_byte, PT_buffer };
static const uint8_t command_parameters18[] PROGMEM = {
    PT_byte, PT_byte };
static const uint8_t command_parameters19[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters20[] PROGMEM = {
    PT_uint32, PT_byte };
static const uint8_t command_parameters21[] PROGMEM = {
    PT_byte };
static const uint8_t command_parameters22[] PROGMEM = {
    PT_byte, PT_uint32 };
static const uint8_t command_parameters23[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_uint32, PT_byte, PT_byte, PT_byte };
static const uint8_t command_parameters24[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_byte };
static const uint8_t command_parameters25[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16, PT_int16 };
static const uint8_t command_parameters26[] PROGMEM = {
    PT_byte, PT_byte, PT_byte };
static const uint8_t command_parameters27[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters28[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_uint32, PT_uint16, PT_uint16, PT_byte };
static const uint8_t command_parameters29[] PROGMEM = {
    PT_byte, PT_buffer, PT_buffer };
static const uint8_t command_parameters30[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters31[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte };
static const uint8_t command_parameters32[] PROGMEM = {
    PT_byte, PT_buffer, PT_byte };
static const uint8_t command_parameters33[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_byte };
static const uint8_t command_parameters34[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters35[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters36[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16, PT_uint32, PT_uint32 };
static const uint8_t command_parameters37[] PROGMEM = {
    PT_byte, PT_buffer, PT_uint32 };
static const uint8_t command_parameters38[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte, PT_uint32, PT_uint32 };
static const uint8_t command_parameters39[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint16, PT_byte, PT_byte, PT_uint16};
static const uint8_t command_parameters40[] PROGMEM = {
    PT_uint32, PT_uint32, PT_uint16};
static const uint8_t command_parameters41[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint16, PT_uint16, PT_uint32};
static const uint8_t command_parameters42[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32};
static const uint8_t command_parameters43[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_uint16, PT_uint32, PT_int32, PT_int32, PT_int32, PT_int32};
static const uint8_t command_parameters44[] PROGMEM = {
    PT_byte, PT_byte, PT_uint32, PT_uint32, PT_byte, PT_byte};
static const uint8_t command_parameters45[] PROGMEM = {
    PT_byte, PT_byte, PT_uint32, PT_uint32};
static const uint8_t command_parameters46[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_byte, PT_byte, PT_byte, PT_byte, PT_byte, PT_byte, PT_byte, PT_byte, PT_byte};
static const uint8_t command_parameters47[] PROGMEM = {
    PT_byte, PT_uint16};
static const uint8_t command_parameters48[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_byte, PT_uint32};

const struct command_encoder command_encoder_66 PROGMEM = {    
    // starting
    .msg_id=66,
    .num_params=0,
    .param_types = 0,
    .max_size=6,
};
const struct command_encoder command_encoder_67 PROGMEM = {    
    // is_shutdown static_string_id=%hu
    .msg_id=67,
    .num_params=1,
    .param_types = command_parameters0,
    .max_size=9,
};
const struct command_encoder command_encoder_68 PROGMEM = {    
    // shutdown clock=%u static_string_id=%hu
    .msg_id=68,
    .num_params=2,
    .param_types = command_parameters1,
    .max_size=14,
};
const struct command_encoder command_encoder_0 PROGMEM = {    
    // identify_response offset=%u data=%.*s
    .msg_id=0,
    .num_params=2,
    .param_types = command_parameters2,
    .max_size=64,
};
const struct command_encoder command_encoder_69 PROGMEM = {    
    // stats count=%u sum=%u sumsq=%u
    .msg_id=69,
    .num_params=3,
    .param_types = command_parameters3,
    .max_size=21,
};
const struct command_encoder command_encoder_70 PROGMEM = {    
    // uptime high=%u clock=%u
    .msg_id=70,
    .num_params=2,
    .param_types = command_parameters4,
    .max_size=16,
};
const struct command_encoder command_encoder_71 PROGMEM = {    
    // clock clock=%u
    .msg_id=71,
    .num_params=1,
    .param_types = command_parameters5,
    .max_size=11,
};
const struct command_encoder command_encoder_72 PROGMEM = {    
    // config is_config=%c crc=%u move_count=%hu is_shutdown=%c
    .msg_id=72,
    .num_params=4,
    .param_types = command_parameters6,
    .max_size=18,
};
const struct command_encoder command_encoder_73 PROGMEM = {    
    // pong data=%*s
    .msg_id=73,
    .num_params=1,
    .param_types = command_parameters7,
    .max_size=64,
};
const struct command_encoder command_encoder_74 PROGMEM = {    
    // debug_result val=%u
    .msg_id=74,
    .num_params=1,
    .param_types = command_parameters5,
    .max_size=11,
};
const struct command_encoder command_encoder_75 PROGMEM = {    
    // stepper_position oid=%c pos=%i
    .msg_id=75,
    .num_params=2,
    .param_types = command_parameters8,
    .max_size=13,
};
const struct command_encoder command_encoder_76 PROGMEM = {    
    // endstop_state oid=%c homing=%c next_clock=%u pin_value=%c
    .msg_id=76,
    .num_params=4,
    .param_types = command_parameters9,
    .max_size=17,
};
const struct command_encoder command_encoder_77 PROGMEM = {    
    // trsync_state oid=%c can_trigger=%c trigger_reason=%c clock=%u
    .msg_id=77,
    .num_params=4,
    .param_types = command_parameters10,
    .max_size=17,
};
const struct command_encoder command_encoder_78 PROGMEM = {    
    // analog_in_state oid=%c next_clock=%u value=%hu
    .msg_id=78,
    .num_params=3,
    .param_types = command_parameters11,
    .max_size=16,
};
const struct command_encoder command_encoder_79 PROGMEM = {    
    // spi_transfer_response oid=%c response=%*s
    .msg_id=79,
    .num_params=2,
    .param_types = command_parameters12,
    .max_size=64,
};
const struct command_encoder command_encoder_80 PROGMEM = {    
    // thermocouple_result oid=%c next_clock=%u value=%u fault=%c
    .msg_id=80,
    .num_params=4,
    .param_types = command_parameters13,
    .max_size=20,
};
const struct command_encoder command_encoder_81 PROGMEM = {    
    // i2c_read_response oid=%c response=%*s
    .msg_id=81,
    .num_params=2,
    .param_types = command_parameters12,
    .max_size=64,
};
const struct command_encoder command_encoder_82 PROGMEM = {    
    // adxl345_end oid=%c end1_clock=%u end2_clock=%u limit_count=%hu sequence=%hu
    .msg_id=82,
    .num_params=5,
    .param_types = command_parameters14,
    .max_size=24,
};
const struct command_encoder command_encoder_83 PROGMEM = {    
    // adxl345_start oid=%c start1_clock=%u start2_clock=%u
    .msg_id=83,
    .num_params=3,
    .param_types = command_parameters15,
    .max_size=18,
};
const struct command_encoder command_encoder_84 PROGMEM = {    
    // adxl345_data oid=%c sequence=%hu data=%*s
    .msg_id=84,
    .num_params=3,
    .param_types = command_parameters16,
    .max_size=64,
};
const struct command_encoder command_encoder_85 PROGMEM = {    
    // buttons_state oid=%c ack_count=%c state=%*s
    .msg_id=85,
    .num_params=3,
    .param_types = command_parameters17,
    .max_size=64,
};
const struct command_encoder command_encoder_86 PROGMEM = {    
    // tmcuart_response oid=%c read=%*s
    .msg_id=86,
    .num_params=2,
    .param_types = command_parameters12,
    .max_size=64,
};
const struct command_encoder command_encoder_87 PROGMEM = {    
    // neopixel_result oid=%c success=%c
    .msg_id=87,
    .num_params=2,
    .param_types = command_parameters18,
    .max_size=10,
};
const struct command_encoder command_encoder_88 PROGMEM = {    
    // counter_state oid=%c next_clock=%u count=%u count_clock=%u
    .msg_id=88,
    .num_params=4,
    .param_types = command_parameters19,
    .max_size=23,
};
const struct command_encoder command_encoder_95 PROGMEM = {
    // lis2dw_status oid=%c clock=%u query_ticks=%u next_sequence=%hu buffered=%c fifo=%c limit_count=%hu
    .msg_id = 95,
    .num_params = 7,
    .param_types = command_parameters39,
    .max_size = 28,
};
const struct command_encoder command_encoder_96 PROGMEM = {
    // lis2dw_data oid=%c sequence=%hu data=%*s
    .msg_id = 96,
    .num_params = 3,
    .param_types = command_parameters16,
    .max_size = 64,
};

const __always_inline struct command_encoder *
ctr_lookup_encoder(const char *str)    //-CMD-G-G-2022-07-21---
{
    if (__builtin_strcmp(str, "starting") == 0)
        return &command_encoder_66;
    if (__builtin_strcmp(str, "is_shutdown static_string_id=%hu") == 0)
        return &command_encoder_67;
    if (__builtin_strcmp(str, "shutdown clock=%u static_string_id=%hu") == 0)
        return &command_encoder_68;
    if (__builtin_strcmp(str, "identify_response offset=%u data=%.*s") == 0)
        return &command_encoder_0;
    if (__builtin_strcmp(str, "stats count=%u sum=%u sumsq=%u") == 0)
        return &command_encoder_69;
    if (__builtin_strcmp(str, "uptime high=%u clock=%u") == 0)
        return &command_encoder_70;
    if (__builtin_strcmp(str, "clock clock=%u") == 0)
        return &command_encoder_71;
    if (__builtin_strcmp(str, "config is_config=%c crc=%u move_count=%hu is_shutdown=%c") == 0)
        return &command_encoder_72;
    if (__builtin_strcmp(str, "pong data=%*s") == 0)
        return &command_encoder_73;
    if (__builtin_strcmp(str, "debug_result val=%u") == 0)
        return &command_encoder_74;
    if (__builtin_strcmp(str, "stepper_position oid=%c pos=%i") == 0)
        return &command_encoder_75;
    if (__builtin_strcmp(str, "endstop_state oid=%c homing=%c next_clock=%u pin_value=%c") == 0)
        return &command_encoder_76;
    if (__builtin_strcmp(str, "trsync_state oid=%c can_trigger=%c trigger_reason=%c clock=%u") == 0)
        return &command_encoder_77;
    if (__builtin_strcmp(str, "analog_in_state oid=%c next_clock=%u value=%hu") == 0)
        return &command_encoder_78;
    if (__builtin_strcmp(str, "spi_transfer_response oid=%c response=%*s") == 0)
        return &command_encoder_79;
    if (__builtin_strcmp(str, "thermocouple_result oid=%c next_clock=%u value=%u fault=%c") == 0)
        return &command_encoder_80;
    if (__builtin_strcmp(str, "i2c_read_response oid=%c response=%*s") == 0)
        return &command_encoder_81;
    if (__builtin_strcmp(str, "adxl345_end oid=%c end1_clock=%u end2_clock=%u limit_count=%hu sequence=%hu") == 0)
        return &command_encoder_82;
    if (__builtin_strcmp(str, "adxl345_start oid=%c start1_clock=%u start2_clock=%u") == 0)
        return &command_encoder_83;
    if (__builtin_strcmp(str, "adxl345_data oid=%c sequence=%hu data=%*s") == 0)
        return &command_encoder_84;
    if (__builtin_strcmp(str, "buttons_state oid=%c ack_count=%c state=%*s") == 0)
        return &command_encoder_85;
    if (__builtin_strcmp(str, "tmcuart_response oid=%c read=%*s") == 0)
        return &command_encoder_86;
    if (__builtin_strcmp(str, "neopixel_result oid=%c success=%c") == 0)
        return &command_encoder_87;
    if (__builtin_strcmp(str, "counter_state oid=%c next_clock=%u count=%u count_clock=%u") == 0)
        return &command_encoder_88;
    if (__builtin_strcmp(str, "lis2dw_status oid=%c clock=%u query_ticks=%u next_sequence=%hu buffered=%c fifo=%c limit_count=%hu") == 0)
        return &command_encoder_95;
    if (__builtin_strcmp(str, "lis2dw_data oid=%c sequence=%hu data=%*s") == 0)
        return &command_encoder_96;
    return NULL;
}

const __always_inline struct command_encoder *
ctr_lookup_output(const char *str)
{
    
    return NULL;
}

extern void command_allocate_oids(uint32_t*);
extern void command_buttons_ack(uint32_t*);
extern void command_buttons_add(uint32_t*);
extern void command_buttons_query(uint32_t*);
extern void command_clear_shutdown(uint32_t*);
extern void command_config_adxl345(uint32_t*);
extern void command_config_analog_in(uint32_t*);
extern void command_config_buttons(uint32_t*);
extern void command_config_counter(uint32_t*);
extern void command_config_digital_out(uint32_t*);
extern void command_config_endstop(uint32_t*);
extern void command_config_hd44780(uint32_t*);
extern void command_config_i2c(uint32_t*);
// extern void command_config_mpu9250(uint32_t*);
extern void command_config_neopixel(uint32_t*);
extern void command_config_pwm_out(uint32_t*);
extern void command_config_spi(uint32_t*);
// extern void command_config_spi_angle(uint32_t*);
extern void command_config_spi_shutdown(uint32_t*);
extern void command_config_spi_without_cs(uint32_t*);
extern void command_config_st7920(uint32_t*);
extern void command_config_stepper(uint32_t*);
extern void command_config_thermocouple(uint32_t*);
extern void command_config_tmcuart(uint32_t*);
extern void command_config_trsync(uint32_t*);
extern void command_debug_nop(uint32_t*);
extern void command_debug_ping(uint32_t*);
extern void command_debug_read(uint32_t*);
extern void command_debug_write(uint32_t*);
extern void command_emergency_stop(uint32_t*);
extern void command_endstop_home(uint32_t*);
extern void command_endstop_query_state(uint32_t*);
extern void command_finalize_config(uint32_t*);
extern void command_get_clock(uint32_t*);
extern void command_get_config(uint32_t*);
extern void command_get_uptime(uint32_t*);
extern void command_hd44780_send_cmds(uint32_t*);
extern void command_hd44780_send_data(uint32_t*);
extern void command_i2c_modify_bits(uint32_t*);
extern void command_i2c_read(uint32_t*);
extern void command_i2c_write(uint32_t*);
extern void command_identify(uint32_t*);
extern void command_neopixel_send(uint32_t*);
extern void command_neopixel_update(uint32_t*);
extern void command_query_adxl345(uint32_t*);
// extern void command_query_adxl345_status(uint32_t*);
extern void command_query_analog_in(uint32_t*);
extern void command_query_counter(uint32_t*);
// extern void command_query_mpu9250(uint32_t*);
// extern void command_query_mpu9250_status(uint32_t*);
// extern void command_query_spi_angle(uint32_t*);
extern void command_query_thermocouple(uint32_t*);
extern void command_queue_digital_out(uint32_t*);
extern void command_queue_pwm_out(uint32_t*);
extern void command_queue_step(uint32_t*);
extern void command_reset(uint32_t*);
extern void command_reset_step_clock(uint32_t*);
extern void command_set_digital_out(uint32_t*);
extern void command_set_digital_out_pwm_cycle(uint32_t*);
extern void command_set_next_step_dir(uint32_t*);
extern void command_set_pwm_out(uint32_t*);
// extern void command_spi_angle_transfer(uint32_t*);
extern void command_spi_send(uint32_t*);
extern void command_spi_set_bus(uint32_t*);
extern void command_spi_set_software_bus(uint32_t*);
extern void command_spi_transfer(uint32_t*);
extern void command_st7920_send_cmds(uint32_t*);
extern void command_st7920_send_data(uint32_t*);
extern void command_stepper_get_position(uint32_t*);
extern void command_stepper_stop_on_trigger(uint32_t*);
extern void command_tmcuart_send(uint32_t*);
extern void command_trsync_set_timeout(uint32_t*);
extern void command_trsync_start(uint32_t*);
extern void command_trsync_trigger(uint32_t*);
extern void command_update_digital_out(uint32_t*);
// extern void command_config_lis2dw(uint32_t*);
// extern void command_query_lis2dw(uint32_t*);
// extern void command_query_lis2dw_status(uint32_t*);

const struct command_parser command_index[] PROGMEM = {
{//-----gg-0-----------
}, {
    // identify offset=%u count=%c
    .msg_id=1,
    .num_params=2,
    .param_types = command_parameters20,
    .num_args=2,
    .flags=0x01,
    .func=command_identify
}, {
    // finalize_config crc=%u
    .msg_id=2,
    .num_params=1,
    .param_types = command_parameters5,
    .num_args=1,
    .flags=0,
    .func=command_finalize_config
}, {
    // config_trsync oid=%c
    .msg_id=3,
    .num_params=1,
    .param_types = command_parameters21,
    .num_args=1,
    .flags=0,
    .func=command_config_trsync
}, {
    // config_buttons oid=%c button_count=%c
    .msg_id=4,
    .num_params=2,
    .param_types = command_parameters18,
    .num_args=2,
    .flags=0,
    .func=command_config_buttons
}, {
    // clear_shutdown
    .msg_id=5,
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_clear_shutdown
}, {
    // set_digital_out pin=%u value=%c
    .msg_id=6,
    .num_params=2,
    .param_types = command_parameters20,
    .num_args=2,
    .flags=0,
    .func=command_set_digital_out
}, {
    // buttons_ack oid=%c count=%c
    .msg_id=7,
    .num_params=2,
    .param_types = command_parameters18,
    .num_args=2,
    .flags=0,
    .func=command_buttons_ack
}, {
    // endstop_query_state oid=%c
    .msg_id=8,
    .num_params=1,
    .param_types = command_parameters21,
    .num_args=1,
    .flags=0,
    .func=command_endstop_query_state
}, {
    // query_adxl345 oid=%c clock=%u rest_ticks=%u
    .msg_id=9,
    .num_params=3,
    .param_types = command_parameters15,
    .num_args=3,
    .flags=0,
    .func=command_query_adxl345
}, {
    // trsync_set_timeout oid=%c clock=%u
    .msg_id=10,
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_trsync_set_timeout
}, {
    // config_spi oid=%c pin=%u
    .msg_id=11,
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_config_spi
}, {
    // get_uptime
    .msg_id=12,
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_uptime
}, {
    // endstop_home oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u pin_value=%c trsync_oid=%c trigger_reason=%c
    .msg_id=13,
    .num_params=8,
    .param_types = command_parameters23,
    .num_args=8,
    .flags=0,
    .func=command_endstop_home
}, {
    // stepper_stop_on_trigger oid=%c trsync_oid=%c
    .msg_id=14,
    .num_params=2,
    .param_types = command_parameters18,
    .num_args=2,
    .flags=0,
    .func=command_stepper_stop_on_trigger
}, {
    // debug_ping data=%*s
    .msg_id=15,
    .num_params=1,
    .param_types = command_parameters7,
    .num_args=2,
    .flags=0x01,
    .func=command_debug_ping
}, {
    // buttons_query oid=%c clock=%u rest_ticks=%u retransmit_count=%c invert=%c
    .msg_id=16,
    .num_params=5,
    .param_types = command_parameters24,
    .num_args=5,
    .flags=0,
    .func=command_buttons_query
}, {
    // queue_step oid=%c interval=%u count=%hu add=%hi
    .msg_id=17,
    .num_params=4,
    .param_types = command_parameters25,
    .num_args=4,
    .flags=0,
    .func=command_queue_step
}, {
    // allocate_oids count=%c
    .msg_id=18,
    .num_params=1,
    .param_types = command_parameters21,
    .num_args=1,
    .flags=0,
    .func=command_allocate_oids
}, {
    // config_endstop oid=%c pin=%c pull_up=%c
    .msg_id=19,
    .num_params=3,
    .param_types = command_parameters26,
    .num_args=3,
    .flags=0,
    .func=command_config_endstop
}, {
    // config_spi_shutdown oid=%c spi_oid=%c shutdown_msg=%*s
    .msg_id=20,
    .num_params=3,
    .param_types = command_parameters17,
    .num_args=4,
    .flags=0,
    .func=command_config_spi_shutdown
}, {
    // config_digital_out oid=%c pin=%u value=%c default_value=%c max_duration=%u
    .msg_id=21,
    .num_params=5,
    .param_types = command_parameters27,
    .num_args=5,
    .flags=0,
    .func=command_config_digital_out
}, {
    // stepper_get_position oid=%c
    .msg_id=22,
    .num_params=1,
    .param_types = command_parameters21,
    .num_args=1,
    .flags=0,
    .func=command_stepper_get_position
}, {
    // st7920_send_data oid=%c data=%*s
    .msg_id=23,
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_st7920_send_data
}, {
    // query_analog_in oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u min_value=%hu max_value=%hu range_check_count=%c
    .msg_id=24,
    .num_params=8,
    .param_types = command_parameters28,
    .num_args=8,
    .flags=0,
    .func=command_query_analog_in
}, {
    // reset_step_clock oid=%c clock=%u
    .msg_id=25,
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_reset_step_clock
}, {
    // i2c_modify_bits oid=%c reg=%*s clear_set_bits=%*s
    .msg_id=26,
    .num_params=3,
    .param_types = command_parameters29,
    .num_args=5,
    .flags=0,
    .func=command_i2c_modify_bits
}, {
    // config_adxl345 oid=%c spi_oid=%c
    .msg_id=27,
    .num_params=2,
    .param_types = command_parameters18,
    .num_args=2,
    .flags=0,
    .func=command_config_adxl345
}, {
    // hd44780_send_data oid=%c data=%*s
    .msg_id=28,
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_hd44780_send_data
}, {
    // buttons_add oid=%c pos=%c pin=%u pull_up=%c
    .msg_id=29,
    .num_params=4,
    .param_types = command_parameters9,
    .num_args=4,
    .flags=0,
    .func=command_buttons_add
}, {
    // trsync_start oid=%c report_clock=%u report_ticks=%u expire_reason=%c
    .msg_id=30,
    .num_params=4,
    .param_types = command_parameters13,
    .num_args=4,
    .flags=0,
    .func=command_trsync_start
}, {
    // config_thermocouple oid=%c spi_oid=%c thermocouple_type=%c
    .msg_id=31,
    .num_params=3,
    .param_types = command_parameters26,
    .num_args=3,
    .flags=0,
    .func=command_config_thermocouple
}, {
    // spi_transfer oid=%c data=%*s
    .msg_id=32,
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_spi_transfer
}, {
    // i2c_write oid=%c data=%*s
    .msg_id=33,
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_i2c_write
}, {
    // reset
    .msg_id=34,
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_reset
}, {
    // config_st7920 oid=%c cs_pin=%u sclk_pin=%u sid_pin=%u sync_delay_ticks=%u cmd_delay_ticks=%u
    .msg_id=35,
    .num_params=6,
    .param_types = command_parameters30,
    .num_args=6,
    .flags=0,
    .func=command_config_st7920
}, {
    // emergency_stop
    .msg_id=36,
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_emergency_stop
}, {
    // neopixel_send oid=%c
    .msg_id=37,
    .num_params=1,
    .param_types = command_parameters21,
    .num_args=1,
    .flags=0,
    .func=command_neopixel_send
}, {
    // spi_set_bus oid=%c spi_bus=%u mode=%u rate=%u
    .msg_id=38,
    .num_params=4,
    .param_types = command_parameters19,
    .num_args=4,
    .flags=0,
    .func=command_spi_set_bus
}, {
    // config_counter oid=%c pin=%u pull_up=%c
    .msg_id=39,
    .num_params=3,
    .param_types = command_parameters31,
    .num_args=3,
    .flags=0,
    .func=command_config_counter
}, {
    // get_clock
    .msg_id=40,
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_clock
}, {
    // tmcuart_send oid=%c write=%*s read=%c
    .msg_id=41,
    .num_params=3,
    .param_types = command_parameters32,
    .num_args=4,
    .flags=0,
    .func=command_tmcuart_send
}, {
    // config_stepper oid=%c step_pin=%c dir_pin=%c invert_step=%c step_pulse_ticks=%u
    .msg_id=42,
    .num_params=5,
    .param_types = command_parameters48,
    .num_args=5,
    .flags=0,
    .func=command_config_stepper
}, {
    // set_digital_out_pwm_cycle oid=%c cycle_ticks=%u
    .msg_id=43,
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_set_digital_out_pwm_cycle
}, {
    // debug_write order=%c addr=%u val=%u
    .msg_id=44,
    .num_params=3,
    .param_types = command_parameters15,
    .num_args=3,
    .flags=0x01,
    .func=command_debug_write
}, {
    // query_counter oid=%c clock=%u poll_ticks=%u sample_ticks=%u
    .msg_id=45,
    .num_params=4,
    .param_types = command_parameters19,
    .num_args=4,
    .flags=0,
    .func=command_query_counter
}, {
    // hd44780_send_cmds oid=%c cmds=%*s
    .msg_id=46,
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_hd44780_send_cmds
}, {
    // spi_set_software_bus oid=%c miso_pin=%u mosi_pin=%u sclk_pin=%u mode=%u rate=%u
    .msg_id=47,
    .num_params=6,
    .param_types = command_parameters30,
    .num_args=6,
    .flags=0,
    .func=command_spi_set_software_bus
}, {
    // neopixel_update oid=%c pos=%hu data=%*s
    .msg_id=48,
    .num_params=3,
    .param_types = command_parameters16,
    .num_args=4,
    .flags=0,
    .func=command_neopixel_update
}, {
    // debug_read order=%c addr=%u
    .msg_id=49,
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0x01,
    .func=command_debug_read
}, {
    // query_thermocouple oid=%c clock=%u rest_ticks=%u min_value=%u max_value=%u
    .msg_id=50,
    .num_params=5,
    .param_types = command_parameters34,
    .num_args=5,
    .flags=0,
    .func=command_query_thermocouple
}, {
    // config_analog_in oid=%c pin=%u
    .msg_id=51,
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_config_analog_in
}, {
    // config_spi_without_cs oid=%c
    .msg_id=52,
    .num_params=1,
    .param_types = command_parameters21,
    .num_args=1,
    .flags=0,
    .func=command_config_spi_without_cs
}, {
    // config_hd44780 oid=%c rs_pin=%u e_pin=%u d4_pin=%u d5_pin=%u d6_pin=%u d7_pin=%u delay_ticks=%u
    .msg_id=53,
    .num_params=8,
    .param_types = command_parameters35,
    .num_args=8,
    .flags=0,
    .func=command_config_hd44780
}, {
    // config_neopixel oid=%c pin=%u data_size=%hu bit_max_ticks=%u reset_min_ticks=%u
    .msg_id=54,
    .num_params=5,
    .param_types = command_parameters36,
    .num_args=5,
    .flags=0,
    .func=command_config_neopixel
}, {
    // spi_send oid=%c data=%*s
    .msg_id=55,
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_spi_send
}, {
    // i2c_read oid=%c reg=%*s read_len=%u
    .msg_id=56,
    .num_params=3,
    .param_types = command_parameters37,
    .num_args=4,
    .flags=0,
    .func=command_i2c_read
}, {
    // trsync_trigger oid=%c reason=%c
    .msg_id=57,
    .num_params=2,
    .param_types = command_parameters18,
    .num_args=2,
    .flags=0,
    .func=command_trsync_trigger
}, {
    // st7920_send_cmds oid=%c cmds=%*s
    .msg_id=58,
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_st7920_send_cmds
}, {
    // get_config
    .msg_id=59,
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_config
}, {
    // set_next_step_dir oid=%c dir=%c
    .msg_id=60,
    .num_params=2,
    .param_types = command_parameters18,
    .num_args=2,
    .flags=0,
    .func=command_set_next_step_dir
}, {
    // config_tmcuart oid=%c rx_pin=%u pull_up=%c tx_pin=%u bit_time=%u
    .msg_id=61,
    .num_params=5,
    .param_types = command_parameters38,
    .num_args=5,
    .flags=0,
    .func=command_config_tmcuart
}, {
    // update_digital_out oid=%c value=%c
    .msg_id=62,
    .num_params=2,
    .param_types = command_parameters18,
    .num_args=2,
    .flags=0,
    .func=command_update_digital_out
}, {
    // queue_digital_out oid=%c clock=%u on_ticks=%u
    .msg_id=63,
    .num_params=3,
    .param_types = command_parameters15,
    .num_args=3,
    .flags=0,
    .func=command_queue_digital_out
}, {
    // config_i2c oid=%c i2c_bus=%u rate=%u address=%u
    .msg_id=64,
    .num_params=4,
    .param_types = command_parameters19,
    .num_args=4,
    .flags=0,
    .func=command_config_i2c
}, {
    // debug_nop
    .msg_id=65,
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_debug_nop
},{}, // 66
    {}, // 67
    {}, // 68
    {}, // 69
    {}, // 70
    {}, // 71
    {}, // 72
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}, // 88
    {   // set_pwm_out pin=%u cycle_ticks=%u value=%hu
     .msg_id = 89,
     .num_params = 3,
     .param_types = command_parameters40,
     .num_args = 3,
     .flags = 0,
     .func = command_set_pwm_out},
    {// queue_pwm_out oid=%c clock=%u value=%hu
     .msg_id = 90,
     .num_params = 3,
     .param_types = command_parameters11,
     .num_args = 3,
     .flags = 0,
     .func = command_queue_pwm_out},
    {// config_pwm_out oid=%c pin=%u cycle_ticks=%u value=%hu default_value=%hu max_duration=%u
     .msg_id = 91,
     .num_params = 6,
     .param_types = command_parameters41,
     .num_args = 6,
     .flags = 0,
     .func = command_config_pwm_out},
    {// query_lis2dw_status oid=%c
    //  .msg_id = 92,
    //  .num_params = 1,
    //  .param_types = command_parameters21,
    //  .num_args = 1,
    //  .flags = 0,
    //  .func = command_query_lis2dw_status
    },
    {// query_lis2dw oid=%c clock=%u rest_ticks=%u
    //  .msg_id = 93,
    //  .num_params = 3,
    //  .param_types = command_parameters15,
    //  .num_args = 3,
    //  .flags = 0,
    //  .func = command_query_lis2dw
    },
    {// config_lis2dw oid=%c spi_oid=%c
    //  .msg_id = 94,
    //  .num_params = 2,
    //  .param_types = command_parameters18,
    //  .num_args = 2,
    //  .flags = 0,
    //  .func = command_config_lis2dw
    },
    {}, // 95
    {}, // 96
    {}, // 97
    {}, // 98
    {}, // 99
    {}, // 100
    {}, // 101
};

const uint8_t command_index_size PROGMEM = ARRAY_SIZE(command_index);

// version: v0.9.1-616-g28f60f7e-dirty-20220408_035823-fluiddpi
// build_versions: gcc: (15:7-2018-q2-6) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907] binutils: (2.31.1-11+rpi1+11) 2.31.1

const uint8_t command_identify_data[] PROGMEM = {
    0x78, 0xda, 0x9d, 0x59, 0x7b, 0x6f, 0x1b, 0xc7,
    0x11, 0xff, 0x2a, 0x5b, 0x02, 0x46, 0xe3, 0x46,
    0x54, 0x79, 0x47, 0xf2, 0x48, 0x0a, 0xf0, 0x1f,
    0x94, 0x2c, 0xc7, 0x41, 0xa3, 0x44, 0x11, 0xa5,
    0xa2, 0x45, 0x10, 0x1c, 0x4e, 0x77, 0x4b, 0x72,
    0xe1, 0x7b, 0xf9, 0x1e, 0x7a, 0x34, 0xd0, 0x77,
    0xef, 0x6f, 0xf6, 0xcd, 0x23, 0xe3, 0x02, 0x35,
    0x20, 0x69, 0xf7, 0x66, 0x76, 0x66, 0x76, 0xde,
    0xb3, 0xfe, 0x63, 0xf4, 0xd8, 0x8b, 0x3c, 0x8b,
    0x9f, 0x78, 0xd3, 0x8a, 0xaa, 0x6c, 0x47, 0x17,
    0xa3, 0x5d, 0x9a, 0x5e, 0xb0, 0xef, 0x82, 0xf9,
    0xc5, 0x62, 0x1c, 0x4e, 0x82, 0xe5, 0xf8, 0x6b,
    0x38, 0x8e, 0xde, 0xb3, 0xc5, 0xf9, 0xf4, 0x3c,
    0x60, 0xf4, 0x61, 0x12, 0x85, 0x21, 0xfb, 0xae,
    0xe1, 0x39, 0x4f, 0x5a, 0xfe, 0x9e, 0xfd, 0xb6,
    0xbe, 0xbb, 0xf9, 0x3b, 0x2f, 0x1e, 0x79, 0x96,
    0xf1, 0x6c, 0xbc, 0x18, 0x3f, 0x36, 0x49, 0x99,
    0xee, 0x59, 0xc3, 0x9f, 0x04, 0x51, 0x64, 0x61,
    0x14, 0xac, 0x26, 0x8b, 0xdf, 0xd9, 0xa3, 0x28,
    0xfb, 0x4e, 0xe4, 0x2d, 0x68, 0x87, 0xe7, 0xd3,
    0xe0, 0x3c, 0x18, 0x07, 0xc1, 0xf7, 0x4d, 0x2d,
    0x82, 0xef, 0x83, 0xe0, 0x3d, 0x53, 0x9f, 0x46,
    0x67, 0xa3, 0xb4, 0x2a, 0x8a, 0xa4, 0xcc, 0x20,
    0xc8, 0x1f, 0xa3, 0x24, 0xcf, 0xab, 0x34, 0xe9,
    0x78, 0x5c, 0x89, 0xac, 0x65, 0x69, 0xd5, 0x97,
    0xdd, 0x87, 0x77, 0xe9, 0xe8, 0x22, 0x58, 0x9e,
    0x41, 0xec, 0xae, 0x83, 0xbc, 0x71, 0x92, 0x7e,
    0x61, 0x00, 0xe3, 0xbb, 0x87, 0xb0, 0xf0, 0xe0,
    0x59, 0x66, 0xe0, 0x75, 0xd5, 0xca, 0x3f, 0xa2,
    0xfc, 0xf0, 0xae, 0x67, 0x75, 0x9f, 0xe7, 0x71,
    0x5f, 0x4b, 0xfc, 0x70, 0xe5, 0x0e, 0x7c, 0xed,
    0x79, 0xf3, 0x6a, 0x49, 0x42, 0x80, 0x2f, 0x84,
    0xdd, 0xf0, 0xb6, 0x8b, 0x3b, 0x91, 0x7e, 0x69,
    0xd5, 0xae, 0xc3, 0x2d, 0xdb, 0x42, 0x74, 0xb1,
    0x61, 0xca, 0x44, 0x09, 0x1d, 0x6a, 0xf9, 0x22,
    0xdc, 0x03, 0xea, 0x69, 0xe2, 0x76, 0xdf, 0x77,
    0x59, 0xf5, 0x5c, 0x8e, 0x2e, 0xe6, 0x74, 0xb5,
    0x72, 0x2b, 0x76, 0x90, 0xe8, 0x25, 0x9f, 0xce,
    0xe6, 0x86, 0x45, 0x5b, 0x8b, 0x58, 0x2d, 0x21,
    0xc7, 0xc2, 0x61, 0x95, 0x49, 0x5e, 0xed, 0x62,
    0x51, 0x5a, 0xe9, 0xa5, 0xd8, 0x20, 0x14, 0x58,
    0x1c, 0x2d, 0xb2, 0xc1, 0x50, 0xdb, 0xd8, 0xa9,
    0x61, 0x66, 0x31, 0xe5, 0x37, 0xde, 0x1c, 0xd2,
    0x3a, 0x50, 0xc1, 0x74, 0x65, 0x91, 0x33, 0xb1,
    0x13, 0x5d, 0x92, 0xc7, 0x55, 0xdf, 0x0d, 0x0e,
    0x3c, 0x25, 0x79, 0xcf, 0x69, 0x9f, 0xf1, 0x6d,
    0xd2, 0xe7, 0x5d, 0x6c, 0x3f, 0x14, 0xc9, 0x4b,
    0x9c, 0xf5, 0x4d, 0xd2, 0xc1, 0xe4, 0x52, 0xcc,
    0xd0, 0x89, 0xc9, 0x61, 0xce, 0xae, 0xaa, 0x0f,
    0x68, 0xa5, 0x07, 0xcc, 0x03, 0xc7, 0x7c, 0x9f,
    0xcd, 0x66, 0x8b, 0xe5, 0xc4, 0x20, 0x37, 0x6d,
    0xac, 0x79, 0x73, 0xb3, 0xc8, 0x66, 0x76, 0x35,
    0xb7, 0xab, 0xc8, 0xae, 0x16, 0x76, 0xc5, 0xf3,
    0xe4, 0xd5, 0xda, 0x0c, 0x8a, 0x9b, 0x5a, 0x26,
    0x22, 0x4c, 0x0d, 0x03, 0x2c, 0xa1, 0x47, 0x65,
    0x55, 0xb8, 0x1a, 0xfd, 0x85, 0xcb, 0xc0, 0xdc,
    0xea, 0x50, 0xe4, 0x74, 0x58, 0xf2, 0xaa, 0x16,
    0x2f, 0x3c, 0x1f, 0xe8, 0x24, 0x4b, 0xba, 0x24,
    0x6e, 0xc5, 0x7f, 0x70, 0x74, 0xdf, 0xc3, 0xcb,
    0xbb, 0x98, 0x74, 0xe1, 0xb9, 0x4a, 0xcb, 0xf1,
    0x49, 0x94, 0xbe, 0x24, 0x8e, 0x28, 0xac, 0x3f,
    0x34, 0x70, 0x10, 0xf8, 0x50, 0xeb, 0x42, 0xc7,
    0xfe, 0xc2, 0x0c, 0x28, 0x2e, 0xda, 0xdd, 0x87,
    0x77, 0x7f, 0x43, 0xcc, 0x84, 0x93, 0x83, 0xb3,
    0xcf, 0xa2, 0xdb, 0xc3, 0x8a, 0x71, 0x6a, 0x7c,
    0x04, 0xbc, 0x43, 0x87, 0xd1, 0x2d, 0x56, 0xa1,
    0xd5, 0x74, 0x6a, 0x35, 0xdd, 0xa6, 0xf9, 0x17,
    0xbb, 0x16, 0x99, 0x5d, 0xbe, 0x96, 0x69, 0x7c,
    0xa8, 0x54, 0x96, 0x16, 0x59, 0x3c, 0xd4, 0xf3,
    0x74, 0xee, 0x71, 0xe0, 0x75, 0xed, 0xdc, 0x8e,
    0xb6, 0xb1, 0x36, 0x7f, 0x26, 0x1a, 0xb3, 0x54,
    0x91, 0x23, 0x91, 0x95, 0xdb, 0x3a, 0x11, 0xbb,
    0x3d, 0x6f, 0x8a, 0x0a, 0xde, 0x5b, 0xe7, 0xfc,
    0x84, 0x02, 0x7c, 0x70, 0xdc, 0xbd, 0xd6, 0x5c,
    0xb9, 0xb2, 0x53, 0x60, 0x57, 0xa4, 0x7d, 0xd2,
    0x58, 0x37, 0x6e, 0x5e, 0xe2, 0x23, 0xd7, 0x67,
    0x9d, 0xfd, 0x48, 0xc6, 0xeb, 0x44, 0xc1, 0x95,
    0xe5, 0x3d, 0x2a, 0x0d, 0xdd, 0xdd, 0xaa, 0x10,
    0x7e, 0x94, 0xf1, 0xc7, 0x1e, 0x1e, 0x51, 0xd5,
    0xc0, 0x9b, 0x9b, 0x2d, 0xa8, 0xec, 0xa4, 0x3b,
    0x28, 0x5b, 0x04, 0x16, 0xd0, 0xf0, 0x04, 0x49,
    0xa8, 0xc9, 0x78, 0x43, 0xfc, 0xc8, 0xbd, 0x24,
    0x87, 0xd9, 0xca, 0x20, 0x3c, 0x37, 0xa2, 0xe3,
    0x47, 0x18, 0x14, 0x6e, 0x0a, 0x11, 0xfe, 0xc2,
    0x0b, 0xde, 0xec, 0x78, 0x99, 0xbe, 0xc6, 0x14,
    0x4b, 0x10, 0x02, 0x39, 0x46, 0x07, 0x56, 0xbc,
    0xaf, 0x0a, 0x7e, 0x94, 0xb1, 0xda, 0xa4, 0x90,
    0x5a, 0x31, 0xa6, 0xd2, 0x7b, 0x9b, 0xaf, 0x0e,
    0x33, 0x1a, 0x64, 0x77, 0xc1, 0xac, 0xee, 0x6b,
    0x95, 0xdc, 0x88, 0xdd, 0x8e, 0x37, 0x74, 0x8b,
    0x96, 0x82, 0x9b, 0xe2, 0x75, 0xea, 0x98, 0xcb,
    0x7c, 0x09, 0xa1, 0x92, 0x8e, 0x5b, 0x0d, 0x21,
    0x3f, 0x6f, 0x05, 0x12, 0x18, 0xa2, 0x22, 0x56,
    0x3a, 0x64, 0x69, 0x93, 0xaa, 0xbc, 0x70, 0x36,
    0xda, 0x21, 0x20, 0xa4, 0x98, 0xb8, 0xd9, 0x44,
    0x6f, 0x25, 0x12, 0xbc, 0x73, 0xa5, 0xf6, 0x7d,
    0x4d, 0x76, 0x00, 0x23, 0xa0, 0xeb, 0x8c, 0x10,
    0xb7, 0xe0, 0x18, 0xc3, 0xe1, 0x6c, 0xbe, 0xa3,
    0xb5, 0x52, 0xf5, 0x2c, 0x1a, 0xa0, 0x91, 0x15,
    0x0c, 0x9a, 0xb3, 0x48, 0x08, 0xb9, 0x28, 0xde,
    0x8b, 0x2a, 0x13, 0xdb, 0xd7, 0x18, 0xe6, 0xb6,
    0xb4, 0x1a, 0x2e, 0x23, 0x88, 0xe9, 0xb4, 0x0d,
    0x11, 0x08, 0xaa, 0x8f, 0x45, 0xea, 0x98, 0x32,
    0xe3, 0x21, 0x3e, 0x7d, 0x8b, 0x73, 0xae, 0x53,
    0xb3, 0x46, 0xd4, 0xe6, 0x1c, 0xb2, 0x9f, 0x42,
    0x6b, 0x22, 0xe3, 0x65, 0x07, 0xe6, 0xac, 0xda,
    0x6e, 0xc1, 0x45, 0xc6, 0x90, 0xab, 0x6b, 0x67,
    0x23, 0x93, 0x64, 0xe4, 0x35, 0x9c, 0xc7, 0x2d,
    0x3c, 0x48, 0x5f, 0x67, 0x4e, 0xd7, 0xaa, 0xa8,
    0xed, 0x7b, 0x8f, 0xcd, 0x0c, 0xb7, 0x54, 0x46,
    0x19, 0x54, 0x9a, 0xd3, 0xc5, 0x6c, 0x74, 0xb1,
    0xb2, 0xf8, 0xc3, 0x9a, 0xf3, 0x7f, 0x3a, 0x53,
    0xe1, 0x9c, 0x09, 0x92, 0x51, 0x3a, 0x74, 0x3b,
    0xd4, 0xcd, 0x1d, 0x0e, 0xee, 0x79, 0xfa, 0xc5,
    0xab, 0x54, 0xe1, 0xcc, 0xc8, 0x30, 0xa8, 0x54,
    0x56, 0x82, 0xba, 0x42, 0xc0, 0x0e, 0xf9, 0xbb,
    0x3b, 0xcc, 0xe6, 0x86, 0xc0, 0xa9, 0x94, 0xf1,
    0x27, 0x65, 0xdc, 0x93, 0xf3, 0x40, 0x4c, 0x32,
    0xe5, 0x44, 0xd2, 0xeb, 0xf9, 0xa9, 0x6a, 0x68,
    0xc9, 0x55, 0x7e, 0x56, 0x8f, 0xa6, 0xe6, 0x08,
    0x65, 0x32, 0x5b, 0x5f, 0xe8, 0x36, 0x2a, 0x90,
    0x8d, 0xa5, 0xf7, 0xb2, 0xc4, 0xe0, 0xaf, 0x80,
    0xc9, 0x61, 0x59, 0x59, 0x22, 0x60, 0xe4, 0x99,
    0x5e, 0xca, 0xf3, 0x2a, 0x42, 0x86, 0x1c, 0xa1,
    0x29, 0x5c, 0x94, 0x70, 0x7c, 0xb1, 0x06, 0xd5,
    0x19, 0xa2, 0x1c, 0xe1, 0xc4, 0xf5, 0x73, 0x11,
    0xa7, 0xaf, 0xa9, 0xa7, 0x13, 0xda, 0xf8, 0x1a,
    0x9c, 0xaa, 0x43, 0x25, 0x7f, 0xd1, 0x12, 0x20,
    0x45, 0x5b, 0x27, 0x16, 0x8d, 0x22, 0x0c, 0xb5,
    0xc8, 0xa2, 0xe4, 0xbc, 0xd3, 0xf3, 0xbc, 0xf9,
    0xdc, 0x40, 0x3b, 0xaa, 0xa9, 0x7e, 0xc2, 0xd6,
    0x25, 0x16, 0x91, 0xc7, 0xbd, 0x52, 0x8b, 0x4b,
    0x2f, 0xdd, 0x91, 0xb6, 0xda, 0x76, 0xcf, 0x49,
    0xc3, 0xfd, 0xb3, 0x85, 0x68, 0x2b, 0x93, 0x9e,
    0x8b, 0xaa, 0x15, 0xa7, 0x6a, 0xd4, 0x11, 0xd1,
    0xd9, 0x42, 0x11, 0x95, 0x4d, 0xda, 0xd6, 0x39,
    0x93, 0x17, 0x8a, 0xc8, 0x2b, 0xaa, 0xfc, 0x7d,
    0x2b, 0xad, 0xcc, 0x97, 0x87, 0x58, 0x7f, 0x92,
    0x55, 0x48, 0x71, 0xaa, 0xd0, 0xc5, 0x94, 0xbb,
    0x10, 0x91, 0x82, 0xda, 0x20, 0x1b, 0xbd, 0x61,
    0xe8, 0x10, 0x64, 0xca, 0x24, 0xb7, 0x51, 0x49,
    0x95, 0xd9, 0x1c, 0xeb, 0x65, 0x5c, 0x78, 0x05,
    0x5c, 0x41, 0x97, 0xae, 0x03, 0x55, 0xcb, 0xc4,
    0x62, 0xf3, 0x8e, 0x2a, 0x96, 0x48, 0x1a, 0xfa,
    0x34, 0xe9, 0x90, 0xd2, 0xe6, 0x09, 0x4f, 0x05,
    0xc9, 0x89, 0xc3, 0xeb, 0xfc, 0x92, 0xc8, 0xeb,
    0xaa, 0xd1, 0xf9, 0x58, 0x45, 0x88, 0xdc, 0xdb,
    0x18, 0xe1, 0x2f, 0xb5, 0x80, 0x49, 0xbc, 0xe4,
    0x3f, 0x75, 0x94, 0x06, 0xb7, 0xf0, 0x90, 0xe6,
    0x30, 0x81, 0x4a, 0x54, 0xa7, 0x02, 0xc8, 0xf3,
    0xd4, 0xf0, 0xcd, 0x94, 0x59, 0xea, 0xf8, 0xd7,
    0x1f, 0xaf, 0xe2, 0x9b, 0xf5, 0xbf, 0xa8, 0x30,
    0xac, 0xe0, 0x4c, 0x97, 0x0f, 0x9b, 0xf8, 0xf6,
    0xc7, 0x9f, 0x37, 0xd4, 0xb0, 0x05, 0x18, 0x4d,
    0x6e, 0x2f, 0xa3, 0xb3, 0xdb, 0xcb, 0xc5, 0x68,
    0x00, 0x49, 0x24, 0x68, 0x09, 0xd0, 0x6a, 0x00,
    0x0a, 0x25, 0x04, 0x77, 0xc7, 0xaf, 0xc0, 0x87,
    0xc1, 0x3d, 0x24, 0xc1, 0x35, 0x08, 0xae, 0x17,
    0xf8, 0x99, 0x0f, 0xa1, 0x8a, 0xe8, 0x0c, 0x27,
    0xe7, 0xf8, 0x99, 0x0e, 0xc0, 0x9a, 0x30, 0x81,
    0x03, 0x82, 0x07, 0x47, 0x08, 0xf2, 0xfc, 0x55,
    0x78, 0x76, 0x7b, 0x35, 0x25, 0xf8, 0x64, 0x00,
    0x9f, 0x7e, 0x93, 0xfc, 0x54, 0x9d, 0x46, 0x2b,
    0x88, 0x5f, 0x44, 0xe3, 0xe8, 0xfc, 0x8c, 0x10,
    0xae, 0x51, 0x88, 0xf1, 0x6b, 0x46, 0xbf, 0x42,
    0x20, 0x5c, 0xfd, 0xf4, 0xcb, 0xd5, 0x3f, 0xe2,
    0x4f, 0x77, 0xd7, 0xbf, 0xd2, 0x90, 0x34, 0x51,
    0xff, 0xce, 0x46, 0x37, 0x57, 0x0f, 0xc0, 0x6e,
    0xbb, 0x62, 0x1a, 0x6e, 0x67, 0xb3, 0xe8, 0xe5,
    0x05, 0xa8, 0x77, 0xd7, 0x9b, 0xeb, 0xbb, 0x7f,
    0x5e, 0x2b, 0x7a, 0x0f, 0x9b, 0x4b, 0xa9, 0x0c,
    0xe2, 0xb7, 0x96, 0x94, 0x0e, 0xc0, 0x69, 0xf3,
    0x0a, 0x9f, 0xc9, 0x09, 0xe5, 0x33, 0x54, 0xf9,
    0x99, 0x34, 0xb9, 0xb9, 0x5f, 0xdf, 0x6f, 0xe2,
    0xcd, 0xc3, 0xcd, 0xe6, 0xd7, 0xf8, 0x72, 0xbd,
    0xb9, 0xa6, 0xcc, 0x14, 0xd1, 0xe7, 0xeb, 0xdb,
    0xf8, 0xe3, 0xf5, 0x4f, 0xeb, 0x7f, 0xe3, 0xc3,
    0x1b, 0x75, 0x09, 0x3d, 0x1a, 0x17, 0x39, 0x16,
    0xc8, 0x91, 0x4e, 0xb7, 0xdb, 0x7a, 0x09, 0x13,
    0x4c, 0x64, 0xc9, 0x24, 0x6d, 0x07, 0x72, 0x15,
    0xaa, 0x73, 0x08, 0x6d, 0xe3, 0x0f, 0xf7, 0xd7,
    0x37, 0xb7, 0xd7, 0x77, 0xeb, 0xfb, 0x87, 0x3b,
    0xc9, 0x04, 0xa1, 0x71, 0xbb, 0x9e, 0x8c, 0x2e,
    0x7e, 0x9b, 0x9c, 0x05, 0xd1, 0xef, 0xd8, 0x5c,
    0xd2, 0x06, 0x23, 0x97, 0xda, 0x5d, 0xd1, 0x0e,
    0xe1, 0xad, 0x76, 0x1f, 0x69, 0x87, 0x82, 0xa8,
    0x76, 0xd7, 0xb4, 0x43, 0x47, 0xaf, 0x76, 0x9f,
    0x68, 0xb7, 0x34, 0x54, 0x7e, 0xa0, 0xdd, 0xca,
    0x50, 0xf9, 0x2c, 0x69, 0x06, 0x92, 0xcc, 0x9b,
    0x4a, 0x26, 0x5a, 0x6a, 0xe5, 0x38, 0x81, 0xfc,
    0x46, 0x52, 0x87, 0x72, 0x15, 0xca, 0x8b, 0x68,
    0xb3, 0x4f, 0xe5, 0x6a, 0x2a, 0xe7, 0x2f, 0x6d,
    0x4b, 0x95, 0x18, 0x61, 0xb3, 0x88, 0xa8, 0xa1,
    0x57, 0x12, 0x14, 0x86, 0x0d, 0x1a, 0xc6, 0x58,
    0x64, 0xfa, 0xa2, 0x4c, 0x06, 0xc8, 0x56, 0x55,
    0x48, 0xd5, 0x75, 0xac, 0x73, 0x8a, 0xf3, 0x57,
    0x66, 0x9a, 0xa9, 0x4c, 0xb5, 0x5e, 0x57, 0x49,
    0xc9, 0xca, 0xaa, 0x63, 0x08, 0x78, 0x46, 0x49,
    0x93, 0x21, 0xb9, 0xab, 0x7c, 0xce, 0x64, 0xdc,
    0xb2, 0xe7, 0xbd, 0xc0, 0x5a, 0xc5, 0x5f, 0xcb,
    0x6a, 0x64, 0x10, 0x70, 0x52, 0xd3, 0x01, 0xce,
    0xfe, 0xb5, 0xa3, 0xfa, 0x83, 0xd6, 0x7e, 0x07,
    0xaa, 0xe8, 0xa1, 0x93, 0x8e, 0x89, 0x96, 0x25,
    0x9a, 0x57, 0x92, 0x76, 0xe2, 0x89, 0xab, 0x42,
    0xa3, 0x91, 0x5b, 0x42, 0xa5, 0xd8, 0x55, 0xc3,
    0x89, 0xfa, 0x2a, 0x4b, 0x15, 0xa3, 0x7c, 0x03,
    0x76, 0xbc, 0x64, 0xa6, 0xd7, 0xb7, 0xe7, 0xa1,
    0x99, 0x2b, 0x35, 0xcc, 0xb3, 0x3a, 0x69, 0x5a,
    0x80, 0x78, 0xd3, 0x54, 0x8d, 0x9c, 0xce, 0x0d,
    0xa0, 0xe1, 0xa8, 0x98, 0x6d, 0x27, 0x3b, 0xc6,
    0x4f, 0x09, 0x84, 0xce, 0x58, 0x57, 0x31, 0x99,
    0xf2, 0x68, 0x46, 0xa3, 0x46, 0x58, 0xcd, 0x03,
    0x3f, 0x96, 0xc8, 0x19, 0x22, 0x63, 0x66, 0xe4,
    0x75, 0x13, 0xb8, 0xaa, 0xaa, 0x2a, 0xa5, 0x1b,
    0x2c, 0xfd, 0x88, 0x20, 0xf5, 0xee, 0xbe, 0x01,
    0x8d, 0x24, 0x49, 0x0a, 0x8e, 0x92, 0xac, 0xf2,
    0xb6, 0x01, 0x16, 0xd5, 0x13, 0x37, 0xc2, 0x30,
    0x1a, 0xe6, 0x54, 0x0e, 0x36, 0x60, 0x3b, 0xfa,
    0xd9, 0x61, 0x4f, 0xf5, 0x64, 0x47, 0x70, 0xdd,
    0x9b, 0x59, 0xfe, 0xd4, 0xa5, 0x1b, 0x24, 0xe8,
    0x8f, 0xd1, 0x8c, 0xa2, 0xba, 0x5a, 0xf3, 0x95,
    0x06, 0x40, 0xe9, 0x5a, 0xb3, 0xf9, 0xe1, 0x47,
    0x93, 0x14, 0x43, 0x8f, 0xcf, 0x41, 0x6f, 0x93,
    0xee, 0x45, 0xad, 0x09, 0x52, 0x4a, 0xbe, 0x49,
    0x5e, 0xc8, 0x7b, 0x96, 0x46, 0x45, 0xaa, 0xa1,
    0xb8, 0xc1, 0x20, 0x9b, 0xec, 0x38, 0xc3, 0xe4,
    0x80, 0x2a, 0x69, 0x2c, 0x00, 0xa9, 0x6e, 0x44,
    0xdb, 0x42, 0xdb, 0x2d, 0x3a, 0xb1, 0xac, 0xcf,
    0x69, 0x72, 0xc1, 0x61, 0xaa, 0xfd, 0x4c, 0xe7,
    0x6b, 0xe9, 0x8e, 0xfc, 0x89, 0x93, 0x6e, 0x69,
    0x98, 0xbf, 0x21, 0x15, 0xc9, 0xfe, 0x86, 0x61,
    0xd5, 0x6c, 0xf3, 0xea, 0x59, 0xcd, 0x38, 0x3f,
    0xc3, 0x13, 0x13, 0xa6, 0x04, 0x24, 0x37, 0x96,
    0xa1, 0x4b, 0x65, 0xc9, 0x07, 0x88, 0xb2, 0x56,
    0x8d, 0x8a, 0x2a, 0xf9, 0x12, 0x54, 0x12, 0x0b,
    0xf7, 0x19, 0x6d, 0xe8, 0x1d, 0xd7, 0xf2, 0x90,
    0x1f, 0xc0, 0xb3, 0x1a, 0x9c, 0xa3, 0x4b, 0xc3,
    0x6c, 0xe4, 0x24, 0x34, 0x2d, 0x6c, 0x2c, 0xc2,
    0x91, 0x9c, 0xec, 0x59, 0xe4, 0x39, 0x0a, 0x56,
    0xca, 0x01, 0xf5, 0x1f, 0x24, 0xd4, 0x03, 0xc3,
    0x06, 0xee, 0xaa, 0x74, 0x23, 0xc9, 0x11, 0x86,
    0x28, 0xfa, 0xc2, 0x7c, 0x33, 0x6e, 0x04, 0xaf,
    0xd8, 0x98, 0x91, 0x5b, 0x4e, 0x03, 0x20, 0x26,
    0x1d, 0x5c, 0x46, 0x9c, 0x7d, 0xcf, 0x81, 0x09,
    0x37, 0xda, 0xe3, 0xbb, 0xaa, 0x62, 0xdb, 0x44,
    0xca, 0xaa, 0xe4, 0xa4, 0x6e, 0xf6, 0xde, 0x37,
    0xd5, 0x89, 0xe8, 0x5e, 0x0d, 0x50, 0x28, 0xf8,
    0x40, 0x4b, 0x3e, 0xab, 0xa8, 0x49, 0xe5, 0x5e,
    0x2a, 0x80, 0x88, 0xa3, 0x38, 0xb7, 0x5c, 0xe6,
    0x95, 0x87, 0xb2, 0xed, 0x6b, 0x2a, 0xd0, 0x5c,
    0x05, 0x88, 0xf2, 0x1c, 0xb0, 0x93, 0x4f, 0x65,
    0x68, 0xab, 0xfb, 0xf2, 0x0b, 0x68, 0x50, 0x20,
    0xa9, 0xde, 0xd2, 0xfb, 0xde, 0x3a, 0x40, 0x64,
    0x47, 0x5b, 0x15, 0xc5, 0x55, 0x99, 0x23, 0xf0,
    0x9f, 0x00, 0x4e, 0x1e, 0x73, 0x13, 0xcf, 0xf6,
    0xaa, 0x2b, 0x99, 0x98, 0x99, 0x6e, 0x2d, 0x54,
    0xa7, 0x38, 0x18, 0xa3, 0x2e, 0xd8, 0x2f, 0xc8,
    0x28, 0xc8, 0xf5, 0x8f, 0xd4, 0x0d, 0x6c, 0x69,
    0x92, 0x6e, 0xff, 0xa2, 0x26, 0x71, 0xf9, 0x76,
    0x67, 0x93, 0x8b, 0x7e, 0xd1, 0xcb, 0x54, 0x43,
    0xd2, 0xd2, 0x30, 0x54, 0x22, 0x6e, 0x94, 0xb1,
    0x53, 0x80, 0x09, 0xe4, 0xba, 0x1f, 0x19, 0x70,
    0x52, 0x07, 0x79, 0xd2, 0x90, 0xde, 0xe8, 0x71,
    0xe1, 0x44, 0x5f, 0x41, 0xb6, 0x51, 0x8e, 0x46,
    0x4f, 0x1e, 0x3a, 0x07, 0x29, 0x6f, 0xa5, 0x4a,
    0x88, 0xa4, 0x7b, 0xf4, 0x54, 0x40, 0x59, 0x17,
    0xad, 0xc6, 0x34, 0x58, 0xce, 0xe7, 0x32, 0x7b,
    0xeb, 0x4d, 0x24, 0xb3, 0xbb, 0xda, 0x44, 0x73,
    0x69, 0x68, 0x6c, 0xa2, 0x68, 0x81, 0xf5, 0xf4,
    0xed, 0x4d, 0xf6, 0xe8, 0x35, 0xe2, 0x8b, 0xab,
    0x27, 0x4a, 0x35, 0x62, 0x1d, 0xb4, 0x86, 0x2d,
    0xe5, 0x91, 0x32, 0xe5, 0x83, 0xb9, 0x6c, 0x49,
    0x66, 0xd2, 0xe8, 0x5e, 0x4f, 0x87, 0x65, 0xe0,
    0xda, 0x2f, 0xec, 0x42, 0xb7, 0xcb, 0x85, 0xf7,
    0xc4, 0x08, 0x62, 0x3e, 0x65, 0x10, 0x0c, 0x1d,
    0xc1, 0x83, 0x9e, 0x4e, 0x6e, 0x3c, 0xa2, 0x72,
    0xef, 0xc8, 0xe2, 0x24, 0x2c, 0x68, 0x87, 0xbd,
    0x83, 0xd9, 0x5d, 0xa6, 0x00, 0x77, 0xd2, 0xce,
    0x6d, 0xc8, 0xda, 0xde, 0xa3, 0xeb, 0xc1, 0x89,
    0xc4, 0x9b, 0xe4, 0x98, 0x84, 0xe8, 0xfb, 0xd2,
    0x3b, 0x90, 0x1c, 0x62, 0x1c, 0xe3, 0x85, 0x7d,
    0x54, 0x41, 0xc9, 0xd1, 0x53, 0xbf, 0xec, 0x53,
    0xe5, 0xeb, 0x80, 0x4c, 0xc3, 0xde, 0x75, 0x81,
    0x62, 0xbc, 0x50, 0x3d, 0xeb, 0xca, 0x87, 0x21,
    0x39, 0x1f, 0x7e, 0x4b, 0x68, 0x4d, 0x40, 0x2f,
    0xfc, 0x6b, 0x2f, 0xdd, 0x8b, 0x4c, 0x8b, 0x38,
    0xb3, 0x0f, 0x2c, 0x8b, 0x99, 0x7b, 0xcf, 0x38,
    0x20, 0xbc, 0xaf, 0x30, 0x23, 0xee, 0x8e, 0x59,
    0xf8, 0xcf, 0x25, 0x38, 0xee, 0x3d, 0x10, 0xc4,
    0xc6, 0x3d, 0x5c, 0x53, 0xac, 0xf6, 0x5a, 0x29,
    0x81, 0x7b, 0x03, 0xf0, 0x50, 0xed, 0x63, 0x80,
    0x72, 0x97, 0x73, 0x42, 0xa5, 0xce, 0xc8, 0x29,
    0x80, 0x0d, 0xbb, 0x06, 0x65, 0x95, 0xc8, 0x7f,
    0x19, 0xd0, 0xb7, 0x32, 0x5e, 0xd0, 0xa7, 0xa9,
    0x7c, 0xc6, 0xa4, 0x07, 0x19, 0xa0, 0x81, 0x95,
    0xff, 0x3c, 0xb5, 0xa0, 0x36, 0xc5, 0x25, 0x3a,
    0xe7, 0x2a, 0xa7, 0xb8, 0x2c, 0x0f, 0x07, 0xaa,
    0xff, 0x71, 0xc9, 0xc5, 0x4a, 0x36, 0x39, 0x4d,
    0x27, 0xbb, 0x8e, 0x28, 0x52, 0x2d, 0x4f, 0xeb,
    0x0c, 0xd3, 0xf6, 0x85, 0xfe, 0xd3, 0x7e, 0x55,
    0xb3, 0xf3, 0xca, 0x8d, 0x48, 0x83, 0xf9, 0x49,
    0xbd, 0x70, 0x60, 0x54, 0x5e, 0xcc, 0x07, 0x51,
    0x7c, 0x78, 0xdd, 0x93, 0x8e, 0xdb, 0xab, 0x84,
    0xaa, 0x74, 0x30, 0x71, 0x43, 0xd5, 0xb1, 0xfc,
    0x34, 0x4e, 0x49, 0x03, 0x45, 0xfe, 0x9c, 0xe4,
    0x3c, 0x21, 0x4d, 0xec, 0xd0, 0x76, 0xf2, 0x51,
    0xcc, 0x77, 0x72, 0x39, 0xfb, 0xc8, 0xce, 0x68,
    0x2f, 0x76, 0x7b, 0xe9, 0x89, 0x0e, 0x38, 0x41,
    0x0a, 0xd1, 0xff, 0xdb, 0x82, 0x86, 0xfa, 0x69,
    0x72, 0xbe, 0x3a, 0x0f, 0xc6, 0x51, 0x10, 0x8d,
    0x77, 0xe1, 0x72, 0x1b, 0x4d, 0xb6, 0x0b, 0x3e,
    0xc6, 0xb4, 0xdd, 0xbd, 0x8e, 0xc3, 0x49, 0x18,
    0x4e, 0x66, 0x93, 0x65, 0x3c, 0x99, 0xce, 0x97,
    0xe1, 0x74, 0xbc, 0xcd, 0x7b, 0x91, 0x65, 0xb5,
    0x18, 0xbd, 0xfd, 0x17, 0xf5, 0xa2, 0x79, 0xcc,
};

// Identify size = 2520 (6581 uncompressed)
const uint32_t command_identify_size PROGMEM
    = ARRAY_SIZE(command_identify_data);
